---
# A playbook that deploys a containerized application(s) onto a single Ubuntu 20.04 LTS Virtual Machine
#
# You can run this playbook with:
#    ansible-playbook -i 123.123.123.123, -e "deployment_name=prod" playbook-app.yml
- hosts: all
  remote_user: root
  vars:
    deploy_private_dir: "./private/{{deployment_name}}/"
    common_server_hostname: "{{deployment_name}}"
  vars_files:
    - "{{deploy_private_dir}}/vars.yml"
  roles:
    # - role: my_app - some app that extends the 'app' role or similar
      